---
#         "ansible_distribution": "Ubuntu",
#        "ansible_distribution_major_version": "15",
#        "ansible_distribution_release": "wily",
#        "ansible_distribution_version": "15.10",

- name: Include OS-specific packages variables.
  include_vars: "{{ item }}"
  with_first_found:
    - "../defaults/required_defaults_{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml"
    - "../defaults/required_defaults_{{ ansible_distribution }}.yml"
    - "../defaults/required_defaults_{{ ansible_os_family }}.yml"

- name: "Update Package Cache"
  apt: update_cache=yes cache_valid_time=3600
  become: yes
  when: ansible_os_family == 'Debian'

- name: "Install packages"
  action: "{{ ansible_pkg_mgr }} name={{ item }}"
  become: yes
  with_items: required_packages

- include: download.yml
