---

- stat: path=/opt/kraken
  register: kraken_installed

- git: repo=http://github.com/Samsung-AG/kraken.git dest=/opt/kraken accept_hostkey=true
  when: kraken_installed.stat.exists == False

- file: path=/opt/kraken/terraform/local/{{ kraken.local_cluster_name }} state=directory
- template: src=terraform.ftvars.j2 dest=/opt/kraken/terraform/local/{{ kraken.local_cluster_name }}/terraform.tfvars

- name: Terraform destroy
  shell: cd /opt/kraken && terraform destroy -force -input=false -state=terraform/local/{{ kraken.local_cluster_name }}/terraform.tfstate -var-file=terraform/local/{{ kraken.local_cluster_name }}/terraform.tfvars terraform/local
  when: not apply_terraform

- name: Terraform apply
  shell: cd /opt/kraken && terraform apply -input=false -state=terraform/local/{{ kraken.local_cluster_name }}/terraform.tfstate -var-file=terraform/local/{{ kraken.local_cluster_name }}/terraform.tfvars terraform/local
  when: apply_terraform

