---

- stat: path={{ kraken_install_path }}
  register: kraken_installed

- git: repo=http://github.com/Samsung-AG/kraken.git dest={{ kraken_install_path }} accept_hostkey=true
  when: kraken_installed.stat.exists == False

- file: path={{ kraken_install_path }}/terraform/local/{{ kraken.local_cluster_name }} state=directory
- template: src=terraform.ftvars.j2 dest={{ kraken_install_path }}/terraform/local/{{ kraken.local_cluster_name }}/terraform.tfvars

- name: Terraform destroy
  become_user: root
  shell: cd {{ kraken_install_path }} && terraform destroy -force -input=false -state=terraform/local/{{ kraken.local_cluster_name }}/terraform.tfstate -var-file=terraform/local/{{ kraken.local_cluster_name }}/terraform.tfvars terraform/local
  when: not apply_terraform

- name: Terraform apply
  become_user: root
  shell: cd {{ kraken_install_path }}  && terraform apply -input=false -state=terraform/local/{{ kraken.local_cluster_name }}/terraform.tfstate -var-file=terraform/local/{{ kraken.local_cluster_name }}/terraform.tfvars terraform/local
  when: apply_terraform

